[package]
name = "sys_call_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
execute = "0.2.8"
nix = "0.25.0"
linux-personality = "1.0"
termion = "1.5.5"
libc = "0.2"